version: '3.9'
services:
  backend:
    build: ./back-end
    container_name: uq-ventures-api
    ports:
      - "8000:8000"
    volumes:
      - ./back-end/fastapi_app:/app/fastapi_app
    depends_on:
      - chromadb

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chromadb
    ports:
      - "8001:8001"

  # If you want local Supabase for dev, you might run it here or use supabase CLI
  # supabase:
  #   image: supabase/local:latest
  #   container_name: supabase
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     # Your Supabase envs here